code_schema:
  bearing_position: 100000
  condition: 1
  fault_size: 10000
  fault_element: 100
  fault_position: 1000
  sampling_rate: 10
dirname: data/cwru
files:
  97: 200021
  98: 200022
  99: 200023
  100: 200024
  101: 100021
  102: 100022
  103: 100023
  104: 100024
  105: 211211
  106: 211212
  107: 211213
  108: 211214
  109: 211221
  110: 211222
  111: 211223
  112: 211224
  118: 211111
  119: 211112
  120: 211113
  121: 211114
  122: 211121
  123: 211122
  124: 211123
  125: 211124
  130: 211311
  131: 211312
  132: 211313
  133: 211314
  135: 211321
  136: 211322
  137: 211323
  138: 211324
  144: 212311
  145: 212312
  146: 212313
  147: 212314
  148: 212321
  149: 212322
  150: 212323
  151: 212324
  156: 213311
  158: 213312
  159: 213313
  160: 213314
  161: 213321
  162: 213322
  163: 213323
  164: 213324
  169: 221211
  170: 221212
  171: 221213
  172: 221214
  174: 221221
  175: 221222
  176: 221223
  177: 221224
  185: 221111
  186: 221112
  187: 221113
  188: 221114
  189: 221121
  190: 221122
  191: 221123
  192: 221124
  197: 221311
  198: 221312
  199: 221313
  200: 221314
  201: 221321
  202: 221322
  203: 221323
  204: 221324
  209: 231211
  210: 231212
  211: 231213
  212: 231214
  213: 231221
  214: 231222
  215: 231223
  217: 231224
  222: 231111
  223: 231112
  224: 231113
  225: 231114
  226: 231121
  227: 231122
  228: 231123
  229: 231124
  234: 231311
  235: 231312
  236: 231313
  237: 231314
  238: 231321
  239: 231322
  240: 231323
  241: 231324
  246: 232311
  247: 232312
  248: 232313
  249: 232314
  250: 232321
  251: 232322
  252: 232323
  253: 232324
  258: 233311
  259: 233312
  260: 233313
  261: 233314
  262: 233321
  263: 233322
  264: 233323
  265: 233324
  270: 131211
  271: 131212
  272: 131213
  273: 131214
  274: 121211
  275: 121212
  276: 121213
  277: 121214
  278: 111211
  279: 111212
  280: 111213
  281: 111214
  282: 111111
  283: 111112
  284: 111113
  285: 111114
  286: 121111
  287: 121112
  288: 121113
  289: 121114
  290: 131111
  291: 131112
  292: 131113
  293: 131114
  294: 111311
  295: 111312
  296: 111313
  297: 111314
  298: 112311
  299: 112312
  300: 112313
  301: 112314
  302: 113311
  305: 113312
  306: 113313
  307: 113314
  309: 122312
  310: 122311
  311: 122313
  312: 122314
  313: 121311
  315: 131311
  316: 132312
  317: 132313
  318: 132314
  3001: 241211
  3002: 241212
  3003: 241213
  3004: 241214
  3005: 241111
  3006: 241112
  3007: 241113
  3008: 241114
filetype: mat
header:
  bearing_position:
    1: FE
    2: DE
  condition:
    1:
      load: 0
      speed: 1797
    2:
      load: 1
      speed: 1772
    3:
      load: 2
      speed: 1750
    4:
      load: 3
      speed: 1730
  fault_size:
    0: 0.0
    1: 0.007
    2: 0.014
    3: 0.021
    4: 0.028
  fault_element:
    0: normal
    1: inner ring
    2: outer ring
    3: ball
  fault_position:
    0: normal
    1: centered
    2: orthogonal
    3: opposite
  sampling_rate:
    1: 12000
    2: 48000
name: cwru
